#   _     __  __            _     _                 
#  | |   |  \/  |          | |   (_)                
#  | |__ | \  / | __ _  ___| |__  _ _ __   ___  ___ 
#  | '_ \| |\/| |/ _` |/ __| '_ \| | '_ \ / _ \/ __|  Desenvolvido por: Markineo
#  | | | | |  | | (_| | (__| | | | | | | |  __/\__ \  Versão: 1.2
#  |_| |_|_|  |_|\__,_|\___|_| |_|_|_| |_|\___||___/
#                                                  
#   

# Define se qualquer pessoa pode recarregar uma máquina/refinaria ou APENAS o dono.
qualquer_um_pode_recarregar: false

# Define em quanto tempo as máquinas vão dropar seus itens [EM TICKS]
# 
# 20 TICKS = 1 SEGUNDO
#
drop_ticks: 100

# 10 segundos para a refinaria
refinaria_drop: 200

# Usado para obter o PREFIXO do player nas mensagens.
player_prefix_placeholder: "%luckperms_prefix%"

#
# Para economiar recursos, as animações só funcionam diante de uma distância específica.
#
# [distância em blocos]
animation_distance: 5

