#   _     __  __            _     _                 
#  | |   |  \/  |          | |   (_)                
#  | |__ | \  / | __ _  ___| |__  _ _ __   ___  ___ 
#  | '_ \| |\/| |/ _` |/ __| '_ \| | '_ \ / _ \/ __|  Desenvolvido por: Markineo
#  | | | | |  | | (_| | (__| | | | | | | |  __/\__ \  Versão: 1.2
#  |_| |_|_|  |_|\__,_|\___|_| |_|_|_| |_|\___||___/
#                                                  
#        

database:
    # Endereço de onde está o banco de dados.
    host: 'localhost'
    port: 3306
    
    # 
    # Tipos possíveis: MySQL/SQLite
    #
    type: 'MySQL'
    
    # Nome do banco de dados
    database: 'harmony'
    user: "root"
    password: ""